### ISSUE TITLE
ukazování pěněz

### ISSUE THREAD

**Issue by jplayr** [m93a/web-textbased-rpg#8]
příklad:
 Máme tady tento krásný meč, máš 50 zlaťáků,⚔️ stojí 100 zlaťáků 💯️ a přidá ti 20 damage ke každému ÚDERU. 🤜️ Chceš ho koupit?

**Comment by detrin** [comment]
[![Dancing Polish Cow 10 Hours](http://img.youtube.com/vi/rRPQs_kM_nw/0.jpg)](http://www.youtube.com/watch?v=rRPQs_kM_nwv "Dancing Polish Cow 10 Hours")
